FROM resin/raspberry-pi3-python:2.7-onbuild

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN apt-get update && apt-get upgrade
RUN apt-get install oracle-java8-jdk
RUN apt-get install python-apt
RUN apt-get install python-gi

CMD ["python", "run"]